/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardDealsIndexRouteImport } from './routes/dashboard/deals/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardMeetingsIdRouteImport } from './routes/dashboard/meetings/$id'
import { Route as DashboardDealsIdRouteImport } from './routes/dashboard/deals/$id'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard/clients/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDealsIndexRoute = DashboardDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeetingsIdRoute = DashboardMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDealsIdRoute = DashboardDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/dashboard/meetings/$id': typeof DashboardMeetingsIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/deals/': typeof DashboardDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/dashboard/meetings/$id': typeof DashboardMeetingsIdRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/deals': typeof DashboardDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/dashboard/meetings/$id': typeof DashboardMeetingsIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/deals/': typeof DashboardDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/calendar'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/dashboard/deals/$id'
    | '/dashboard/meetings/$id'
    | '/dashboard/clients/'
    | '/dashboard/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/calendar'
    | '/dashboard'
    | '/dashboard/clients/$id'
    | '/dashboard/deals/$id'
    | '/dashboard/meetings/$id'
    | '/dashboard/clients'
    | '/dashboard/deals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/calendar'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/dashboard/deals/$id'
    | '/dashboard/meetings/$id'
    | '/dashboard/clients/'
    | '/dashboard/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/deals/': {
      id: '/dashboard/deals/'
      path: '/deals'
      fullPath: '/dashboard/deals/'
      preLoaderRoute: typeof DashboardDealsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/meetings/$id': {
      id: '/dashboard/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/dashboard/meetings/$id'
      preLoaderRoute: typeof DashboardMeetingsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/deals/$id': {
      id: '/dashboard/deals/$id'
      path: '/deals/$id'
      fullPath: '/dashboard/deals/$id'
      preLoaderRoute: typeof DashboardDealsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/clients/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
  DashboardDealsIdRoute: typeof DashboardDealsIdRoute
  DashboardMeetingsIdRoute: typeof DashboardMeetingsIdRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardDealsIndexRoute: typeof DashboardDealsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsIdRoute: DashboardClientsIdRoute,
  DashboardDealsIdRoute: DashboardDealsIdRoute,
  DashboardMeetingsIdRoute: DashboardMeetingsIdRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardDealsIndexRoute: DashboardDealsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
